# Generated by Django 3.1.6 on 2021-04-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment Text')),
                ('number_of_stars', models.IntegerField(choices=[(1, 'One-Star'), (2, 'Two-Star'), (3, 'Three-Star'), (4, 'Four-Star'), (5, 'Five-Star')], verbose_name='Number of stars')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
