# Generated by Django 3.1.6 on 2021-05-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reservation_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomphoto',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='api.room', verbose_name='Room'),
        ),
    ]
