# Generated by Django 3.1.6 on 2021-05-14 15:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210514_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(validators=[api.models.is_valid_date], verbose_name='Check In'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(validators=[api.models.is_valid_date], verbose_name='Check Out'),
        ),
    ]
