# Generated by Django 3.1.6 on 2021-05-15 01:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210514_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(validators=[api.models.is_valid_comment], verbose_name='Comment Text'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.IntegerField(validators=[api.models.is_valid_number], verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.IntegerField(validators=[api.models.is_valid_number], verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='room',
            name='cost',
            field=models.IntegerField(validators=[api.models.is_valid_number], verbose_name='Cost'),
        ),
    ]
