# Generated by Django 3.1.6 on 2021-05-15 04:04

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210515_0953'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reservation',
            managers=[
                ('objects', api.models.ReservationManager()),
            ],
        ),
    ]
