# Generated by Django 3.1.6 on 2021-05-14 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0004_auto_20210513_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+777777777777'. Up to 15 digits                                  allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
